src/main/java/com/com/ablsystem/model/Visitante.java
package com.com.ablsystem.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.br.CPF;

@Entity
public class Visitante implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	private Long id;

	@NotEmpty
	@Column(nullable = false, length = 80)
	private String nome;
	
	@NotEmpty
	@CPF
	@Column(nullable = false, length = 14)
	private String cpf;
	
	@Column(length = 20)
	private String telefone;
	
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_visita")
	private Date dataVisita;
	
	@NotNull
	@Lob
	@Column(nullable = false)
	private byte[] foto;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public Date getDataVisita() {
		return dataVisita;
	}

	public void setDataVisita(Date dataVisita) {
		this.dataVisita = dataVisita;
	}

	public byte[] getFoto() {
		return foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Visitante other = (Visitante) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
}

src/main/java/com/ablsystem/controller/FotoCameraBean.java
package com.ablsystem.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.primefaces.event.CaptureEvent;
import org.primefaces.model.ByteArrayContent;
import org.primefaces.model.StreamedContent;

@Named
@SessionScoped
public class FotoCameraBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private StreamedContent fotoContent;
	private byte[] fotoBytes;
	
	public void limpar() {
		fotoContent = null;
		fotoBytes = null;
	}
	
	public void aoCapturarFoto(CaptureEvent event) {
		fotoBytes = event.getData();
		fotoContent = new ByteArrayContent(fotoBytes, "image/jpeg");
	}

	public StreamedContent getFotoContent() {
		return fotoContent;
	}

	public byte[] getFotoBytes() {
		return fotoBytes;
	}
	
	public boolean isFotoCapturada() {
		return getFotoContent() != null;
	}
	
}

src/main/java/com/ablsystem/controller/FotoVisitanteServlet.java
package com.ablsystem.controller;

import java.io.IOException;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.io.IOUtils;

import com.com.ablsystem.model.Visitante;
import com.com.ablsystem.repository.Visitantes;

@WebServlet(urlPatterns = "/foto-visitante")
public class FotoVisitanteServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	@Inject
	private Visitantes visitantes;
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) 
			throws ServletException, IOException {
		Long idVisitante = Long.valueOf(req.getParameter("visitante"));
		
		Visitante visitante = visitantes.porId(idVisitante);
		
		resp.setContentType("image/jpeg");
		IOUtils.write(visitante.getFoto(), resp.getOutputStream());
	}
	
}

src/main/java/com/ablsystem/controller/RegistroVisitanteBean.java
package com.ablsystem.controller;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.com.ablsystem.model.Visitante;
import com.com.ablsystem.repository.Visitantes;

@Named
@ViewScoped
public class RegistroVisitanteBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private FotoCameraBean fotoCamera;
	
	@Inject
	private Visitantes visitantes;
	
	private Visitante visitante;
	
	private List<Visitante> todosVisitantes;

	public void consultar() {
		todosVisitantes = visitantes.todos();
	}
	
	public void novo() {
		visitante = new Visitante();
		fotoCamera.limpar();
	}
	
	public void adicionar() {
		visitante.setDataVisita(new Date());
		visitante.setFoto(fotoCamera.getFotoBytes());
		
		visitantes.guardar(visitante);
		
		consultar();
		
		FacesMessage msg = new FacesMessage("Visitante registrado!");
		FacesContext.getCurrentInstance().addMessage(null, msg);
		
		RequestContext.getCurrentInstance().execute("PF('novoVisitanteDialog').hide()");
		RequestContext.getCurrentInstance().update("frm:msgs-geral");
	}
	
	public Visitante getVisitante() {
		return visitante;
	}

	public List<Visitante> getTodosVisitantes() {
		return todosVisitantes;
	}
	
}

src/main/webapp/controleacesso.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
	<h:head>
	  <meta charset="UTF-8"/>
	  <title>Controle de Acesso</title>
	  <h:outputStylesheet library="ablsystem" name="estilo.css" />
	</h:head>

	<h:body>
	
		<f:metadata>
			<f:viewAction action="#{registroVisitanteBean.consultar}"/>
		</f:metadata>
	
		<h:form id="frm">
			
			<p:growl id="msgs-geral"/>
		
			<header>
				<p:panelGrid columns="1" layout="grid" style="padding: 1px;">
					<!-- <h:graphicImage library="ablsystem" name="logo-csc.png" style="width: 50px;"/> -->
					<h1>CONTROLE DE VISITANTES NA UNIDADE</h1>
				</p:panelGrid>
				
			</header>
			<div id="conteudo">
				<div style="text-align: center; margin-bottom: 15px;">
					<p:commandButton value="Novo visitante"
						action="#{registroVisitanteBean.novo()}"
						update="painel-dialogo" process="@this"
						onsuccess="PF('novoVisitanteDialog').show(); return false;">
							<p:resetInput target="novo-visitante-dialogo"/>
						</p:commandButton>
				</div>
				<p:dataGrid value="#{registroVisitanteBean.todosVisitantes}" var="visitante" emptyMessage=""
					columns="4" layout="grid" id="grid-visitantes">
					<p:panel header="#{visitante.nome}" style="text-align: center">
						<h:graphicImage value="/foto-visitante?visitante=#{visitante.id}" />
						<br/>Entrada: 
						<h:outputText value="#{visitante.dataVisita}">
							<f:convertDateTime pattern="HH:mm:ss"/>
						</h:outputText>
					</p:panel>
					
				</p:dataGrid>
			</div>
		
			<p:dialog widgetVar="novoVisitanteDialog" 
				header="Novo visitante" 
				resizable="false" 
				modal="true" id="novo-visitante-dialogo"
				dynamic="true">
				<h:panelGroup id="painel-dialogo">
					<p:messages id="msg-dialogo"/>
					<h:panelGrid columns="2">
						<h:panelGroup style="text-align: center;" layout="block" id="painel-foto">
							<p:photoCam widgetVar="camera" width="300" format="jpeg" 
								listener="#{fotoCameraBean.aoCapturarFoto}"
								update="painel-foto btn-registrar"
								rendered="#{not fotoCameraBean.fotoCapturada}"/>
							<p:commandLink value="Capturar foto" 
								rendered="#{not fotoCameraBean.fotoCapturada}" 
								onclick="PF('camera').capture(); return false;" />
							<p:graphicImage value="#{fotoCameraBean.fotoContent}" cache="false" 
								rendered="#{fotoCameraBean.fotoCapturada}"/>
						</h:panelGroup>
						
						<h:panelGrid columns="1" style="margin-left: 10px;">
							<p:outputLabel value="Nome" for="nome"/>
							<p:inputText size="30" id="nome" value="#{registroVisitanteBean.visitante.nome}"/>
							
							<p:outputLabel value="CPF" for="cpf"/>
							<p:inputMask size="14" mask="999.999.999-99" id="cpf" value="#{registroVisitanteBean.visitante.cpf}"/>
							
							<p:outputLabel value="Telefone celular" for="telefonecelular"/>
							<p:inputMask size="15" mask="(99) 99999-9999" id="telefonecelular" value="#{registroVisitanteBean.visitante.telefone}"/>
							
							<p:commandButton value="Registrar" icon="fa fa-save" 
								id="btn-registrar"
								update="painel-dialogo grid-visitantes"
								action="#{registroVisitanteBean.adicionar}"
								disabled="#{not fotoCameraBean.fotoCapturada}"/>
						</h:panelGrid>
					</h:panelGrid>
				</h:panelGroup>
			</p:dialog>
		</h:form>
	</h:body>
</html>